======== error test ========
 [0,0,0] [0,0,1] [0,0,2] [0,1,0] [0,1,1] [0,1,2] [0,2,0] [0,2,1] [0,2,2] [1,0,0] [1,0,1] [1,0,2] [1,1,0] [1,1,1] [1,1,2] [1,2,0] [1,2,1] [1,2,2] [2,0,0] [2,0,1] [2,0,2]except(IteratorError)
end-of-function
 [0,0,0] [0,0,1] [0,0,2] [0,1,0] [0,1,1] [0,1,2] [0,2,0] [0,2,1] [0,2,2] [1,0,0] [1,0,1] [1,0,2] [1,1,0] [1,1,1] [1,1,2] [1,2,0] [1,2,1] [1,2,2] [2,0,0] [2,0,1] [2,0,2]except()
end-of-function
 [0,0,0] [0,0,1] [0,0,2] [0,1,0] [0,1,1] [0,1,2] [0,2,0] [0,2,1] [0,2,2] [1,0,0] [1,0,1] [1,0,2] [1,1,0] [1,1,1] [1,1,2] [1,2,0] [1,2,1] [1,2,2] [2,0,0] [2,0,1] [2,0,2] [2,1,0] [2,1,1] [2,1,2] [2,2,0] [2,2,1] [2,2,2]else
end-of-function
  1  3  5  7  9
end-of-function
  0  1  2  3  4  5  6  7  8
end-of-function
try
expected error occurs: TypeError: variable 'p' cannot take list value in 'p:Person'
ValueError detected: ValueError: undefined symbol 'a'
other error detected: IndexError: index is out of range
no error
except(IndexError) .. IndexError: intentional error for handling test
except(ValueError) .. ValueError: intentional error for handling test
except(IOError) .. IOError: intentional error for handling test
except(SystemError, CodecError) .. SystemError: intentional error for handling test
except(SystemError, CodecError) .. CodecError: intentional error for handling test
except() .. AttributeError: intentional error for handling test
else()
ValueError detected: ValueError: unhandled error
